language: python
dist: xenial

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy" # CPython 2.7

env:
  - DJANGO="1.8"
  - DJANGO="1.9"
  - DJANGO="1.10"
  - DJANGO="1.11"

# command to install dependencies
install:
    - pip install six tox-travis

# command to run tests
script:
    - tox
